import { FC } from 'react'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import Header from '../header'

interface prop {
  children: string,
}

export const Layout:FC<prop> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
      {children}
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}

